### ISSUE TITLE
BUG: Running example code results in `AttributeError`

### ISSUE THREAD

**Issue by bluginbuhl** [dylanwal/chemdraw#3]
Running the example code below from the PyPI page

```python
import chemdraw

mol = "O=C(C)Oc1ccccc1C(=O)O"
drawer = chemdraw.Drawer(mol, title=mol)
fig = drawer.draw()
fig.show()
```

results in the following stack trace:

```
Traceback (most recent call last):
  File "/.../testing/chemdraw-test/example.py", line 6, in <module>
    fig = drawer.draw()
  File "/.../testing/chemdraw-test/.venv/lib/python3.10/site-packages/chemdraw/drawers/drawer.py", line 112, in draw
    fig = self._draw(fig)
  File "/.../testing/chemdraw-test/.venv/lib/python3.10/site-packages/chemdraw/drawers/drawer.py", line 121, in _draw
    self.config.layout.get_scaling(self.molecule, self.title)
  File "/.../testing/chemdraw-test/.venv/lib/python3.10/site-packages/chemdraw/drawers/layout.py", line 64, in get_scaling
    if self.fixed_domain and self.range_y.ptp() != self.range_x.ptp():
AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.
```

To fix this, either the new `ptp` API should be used, or the version number for `numpy` should be pinned to be `>=1.23.1,<=2.0`.

**Comment by dylanwal** [comment]
Thanks for letting me know! I pushed an update with support for numpy 2.0 syntax.
